# Generated by Django 2.1.2 on 2018-10-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppc_UniqueMerchantTxnID', models.CharField(max_length=200)),
                ('ppc_Amount', models.CharField(max_length=200)),
                ('ppc_MerchantID', models.CharField(max_length=200)),
                ('ppc_MerchantAccessCode', models.CharField(max_length=200)),
                ('ppc_NavigationMode', models.CharField(max_length=200)),
                ('ppc_TransactionType', models.CharField(max_length=200)),
                ('ppc_LPC_SEQ', models.CharField(max_length=200)),
                ('ppc_ProductCode', models.CharField(max_length=200)),
                ('ppc_MerchantReturnURL', models.CharField(max_length=200)),
                ('ppc_PayModeOnLandingPage', models.CharField(max_length=200)),
                ('ppc_DIA_SECRET', models.CharField(max_length=200)),
                ('ppc_DIA_SECRET_TYPE', models.CharField(max_length=200)),
            ],
        ),
    ]
