# Generated by Django 3.1.1 on 2020-09-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantTestPage',
        ),
    ]
