# Generated by Django 3.1.1 on 2020-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testmerchantapp', '0002_delete_merchanttestpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=200)),
                ('merchant_access_code', models.CharField(max_length=200)),
                ('merchant_secret_key', models.CharField(max_length=200)),
                ('merchant_return_url', models.CharField(max_length=200)),
                ('preferred_payment_gateway', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('amount_in_paisa', models.CharField(max_length=200)),
                ('order_description', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('bill_first_name', models.CharField(max_length=200)),
                ('bill_last_name', models.CharField(max_length=200)),
                ('bill_address1', models.CharField(max_length=200)),
                ('bill_address2', models.CharField(max_length=200)),
                ('bill_address3', models.CharField(max_length=200)),
                ('bill_pincode', models.CharField(max_length=200)),
                ('bill_city', models.CharField(max_length=200)),
                ('bill_state', models.CharField(max_length=200)),
                ('bill_country', models.CharField(max_length=200)),
                ('ship_first_name', models.CharField(max_length=200)),
                ('ship_last_name', models.CharField(max_length=200)),
                ('ship_address1', models.CharField(max_length=200)),
                ('ship_address2', models.CharField(max_length=200)),
                ('ship_address3', models.CharField(max_length=200)),
                ('ship_pincode', models.CharField(max_length=200)),
                ('ship_city', models.CharField(max_length=200)),
                ('ship_state', models.CharField(max_length=200)),
                ('ship_country', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('product_amount_in_paisa', models.CharField(max_length=200)),
                ('rfu1', models.CharField(max_length=200)),
            ],
        ),
    ]
