# Generated by Django 3.1.1 on 2020-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0003_merchanttestpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchanttestpage',
            name='rfu1',
        ),
    ]
