# Generated by Django 3.1.1 on 2020-09-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0004_remove_merchanttestpage_rfu1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_address1',
            new_name='billing_address1',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_address2',
            new_name='billing_address2',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_address3',
            new_name='billing_address3',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_first_name',
            new_name='billing_first_name',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_last_name',
            new_name='billing_last_name',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_pincode',
            new_name='billing_pincode',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='bill_state',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_address2',
            new_name='shipping_address2',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_address3',
            new_name='shipping_address3',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_first_name',
            new_name='shipping_first_name',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_last_name',
            new_name='shipping_last_name',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_pincode',
            new_name='shipping_pincode',
        ),
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='ship_state',
            new_name='shipping_state',
        ),
    ]
