# Generated by Django 3.1.1 on 2020-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0005_auto_20200909_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttestpage',
            name='payment_modes_csv',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
