# Generated by Django 3.1.1 on 2020-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0006_merchanttestpage_payment_modes_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttestpage',
            name='gateway_mode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
