# Generated by Django 3.1.1 on 2020-09-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmerchantapp', '0009_merchanttestpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchanttestpage',
            old_name='gateway_mode',
            new_name='is_production',
        ),
    ]
